version: '2.2'

services:

    router:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./front-end/dist:/home/docker/workspace/front-end/dist
        ports:
            - "8088:80"
        mem_limit: 400m

    mongo:
        image: mongo:3
        ports:
            - "27018:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoroot
            - MONGO_INITDB_ROOT_PASSWORD=qweq9t6i8cnca6xm
            - MONGO_INITDB_DATABASE=qiibee

    rest-api:
        build: ./rest-api
        environment:
            - MONGO_USER=mongoroot
            - MONGO_PASSWORD=qweq9t6i8cnca6xm
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DBNAME=qiibee


